@startuml
    class Flight {
        number
        departure time
        arrival time
        visibility on arrival
    }

    class Airport {
        code
        name
    }
    
    class Employment {
        year
        number of employees
    }

    class Aircraft {
        registration
        serial number
        age
        type
    }

    Flight "0..*" -right-> "1" Airport : departs from
    Flight "0..*" -right-> "1" Airport : arrives to
    Flight "0..*" -left-> "0..1" Aircraft : has aircraft
    Airport "1" -right-> "0..*" Employment : has employment
@enduml