@startuml
    class TrainTrip {
        departure platform
        arrival platform
    }
    
    class Station
    
    class Train {
        name
    }
    
    TrainTrip "0..*" -right-> "1" Station : departs from
    TrainTrip "0..*" -right-> "1" Station : arrives to
    TrainTrip "0..*" -left-> "0..1" Train : has train
    
    class CivicStructure {
        code
        name
    }
    
    class Trip {
        departure time
        arrival time
    }
    
    class Vehicle {
        number
    }
    
    class Employment {
        year
        number of employees
    }
    
    Trip "0..*" -right-> "1" CivicStructure : departs from
    Trip "0..*" -right-> "1" CivicStructure : arrives to
    Trip "0..*" -left-> "0..*" Vehicle : has vehicle
    
    CivicStructure "1" -right-> "0..*" Employment : has employment
    
    class Flight {
        number
        visibility on arrival
    }
    
    class Airport
    class Aircraft {
        registration
        serial number
        age
        type
    }
    
    Flight "0..*" -right-> "1" Airport : departs from
    Flight "0..*" -right-> "1" Airport : arrives to
    Flight "0..*" -left-> "0..1" Aircraft : has aircraft
    
    Vehicle <|-- Aircraft
    Trip <|-- Flight
    CivicStructure <|-- Airport
    
    Train --|> Vehicle
    TrainTrip --|> Trip
    Station --|> CivicStructure
@enduml