@startuml
    class Flight {
        arrivalGate
        arrivalTerminal
        departureGate
        departureTerminal
        estimatedFlightDuration
        flightDistance
        flightNumber
        mealService
        webCheckingTime
    }

    class Trip {
        arrivalTime
        departureTime
    }

    class Intangible {

    }

    class Thing {
        alternateName
        description
        identifier
        name
    }
    
    Flight -up-|> Trip
    Trip -up-|> Intangible
    Intangible -up-|> Thing

    Flight --> Vehicle : aircraft
    Flight --> Airport : arrivalAirport
    Flight --> Airport : departureAirport
    Flight --> Organization : seller
    Flight --> Person : seller

    Trip --> Place : itinerary
    Trip --> Demand : offers
    Trip --> Offer : offers
    Trip --> Trip : partOfTrip
    Trip --> Organization : provider
    Trip --> Person : provider
    Trip --> Trip : subTrip
@enduml