@startuml
    class Flight {
        number
        duration
    }

    class FlightEvent {
        scheduled
        estimated
        actual
        visibility
    }
    
    class Airport {
        code
        name
    }
    
    Flight "1" --> "1" FlightEvent : has departure
    Flight "1" --> "1" FlightEvent : has arrival
    FlightEvent "0..*" -left-> "1" Airport : location
@enduml
