@startuml
    class Flight {
        number
    }

    class FlightEvent {
        scheduled time
        estimated time
        actual time
        visibility
    }
    
    class Airport {
        code
        name
    }
    
    class Aircraft {
        registration
        serial number
        age
    }
    
    Flight "0..*" --> "0..1" Aircraft : has aircraft
    Flight "1" --> "1" FlightEvent : has departure
    Flight "1" --> "1" FlightEvent : has arrival
    Flight "1" --> "0..*" FlightEvent : has event
    FlightEvent "0..*" -left-> "1" Airport : happened at
@enduml
