@startuml
    class TrainTrip {
        departure time
        departure platform
        arrival time
        arrival platform
    }
    
    class Station {
        code
        name
    }
    
    class Employment {
        year
        number of employees
    }
    
    class Train {
        name
        number
    }
    
    TrainTrip "0..*" -right-> "1" Station : departs from
    TrainTrip "0..*" -right-> "1" Station : arrives to
    TrainTrip "0..*" -left-> "0..1" Train : has train
    Station "1" -right-> "0..*" Employment : has employment
@enduml